/obj/structure/retail/clothing_store/Initialize()
	. = ..()
	products_list += new /datum/data/vending_product("black choker", /obj/item/clothing/neck/vampire/choker, 25)
	products_list += new /datum/data/vending_product("metallic choker", /obj/item/clothing/neck/vampire/choker/metal, 25)
	products_list += new /datum/data/vending_product("leather choker", /obj/item/clothing/neck/vampire/choker/leather, 25)
	products_list += new /datum/data/vending_product("silver-chain choker", /obj/item/clothing/neck/vampire/choker/silver, 25)
	products_list += new /datum/data/vending_product("fancy choker", /obj/item/clothing/neck/vampire/choker/fancy, 25)
	products_list += new /datum/data/vending_product("aviators", /obj/item/clothing/glasses/vampire/aviator, 20)
	products_list += new /datum/data/vending_product("green aviators", /obj/item/clothing/glasses/vampire/aviator/green, 20)
	products_list += new /datum/data/vending_product("blue aviators", /obj/item/clothing/glasses/vampire/aviator/blue, 20)
	products_list += new /datum/data/vending_product("oversized sunglasses", /obj/item/clothing/glasses/vampire/sun/oversized, 20)
	products_list += new /datum/data/vending_product("thin sunglasses", /obj/item/clothing/glasses/vampire/sun/thin, 20)
	products_list += new /datum/data/vending_product("green prescription glasses", /obj/item/clothing/glasses/vampire/perception/green, 20)
	products_list += new /datum/data/vending_product("retro glasses", /obj/item/clothing/glasses/vampire/perception/retro, 20)
	products_list += new /datum/data/vending_product("metal-framed prescription glasses", /obj/item/clothing/glasses/vampire/perception/metal, 20)
	products_list += new /datum/data/vending_product("bicolor glasses", /obj/item/clothing/glasses/vampire/misc/bicolor, 20)
	products_list += new /datum/data/vending_product("safety goggles", /obj/item/clothing/glasses/vampire/misc/safety, 20)
	products_list += new /datum/data/vending_product("bucket hat", /obj/item/clothing/head/vampire/hat/bucket, 25)
	products_list += new /datum/data/vending_product("boater hat", /obj/item/clothing/head/vampire/hat/boater, 25)
	products_list += new /datum/data/vending_product("beaver hat", /obj/item/clothing/head/vampire/hat/beaver, 25)
	products_list += new /datum/data/vending_product("white wool hat", /obj/item/clothing/head/vampire/hat/wool, 25)
	products_list += new /datum/data/vending_product("blue and white wool hat", /obj/item/clothing/head/vampire/hat/wool/blue, 25)
	products_list += new /datum/data/vending_product("picture hat", /obj/item/clothing/head/vampire/hat/picture, 25)
	products_list += new /datum/data/vending_product("red picture hat", /obj/item/clothing/head/vampire/hat/picture/red, 25)

/obj/structure/retail/costume_store/Initialize()
	. = ..()
	products_list += new /datum/data/vending_product("right eyepatch", /obj/item/clothing/glasses/vampire/misc/eyepatch, 25)
	products_list += new /datum/data/vending_product("left eyepatch", /obj/item/clothing/glasses/vampire/misc/eyepatch/left, 25)
	products_list += new /datum/data/vending_product("right medical eyepatch", /obj/item/clothing/glasses/vampire/misc/eyepatch/medical, 25)
	products_list += new /datum/data/vending_product("left medical eyepatch", /obj/item/clothing/glasses/vampire/misc/eyepatch/medical_left, 25)
	products_list += new /datum/data/vending_product("white veil", /obj/item/clothing/glasses/vampire/misc/veil, 25)
	products_list += new /datum/data/vending_product("black veil", /obj/item/clothing/glasses/vampire/misc/veil/black, 25)
	products_list += new /datum/data/vending_product("frilly headband", /obj/item/clothing/head/vampire/headband_frilly, 25)
	products_list += new /datum/data/vending_product("black headdress", /obj/item/clothing/head/vampire/headdress_black, 25)
